# Generated by Django 4.1.3 on 2022-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('sky', models.CharField(max_length=100)),
            ],
        ),
    ]
